#pragma once

namespace OBJ
{
	enum ID { SHADOW, POTAL, MONSTER_BACK, BEAM, BOSS, MONSTER, BACK, ROCK, BULLET
		, FURNITURE, NPC, CHEST, PILLAR, TOWN_PLAYER, PLAYER, WEAPON, ARROW, EFFECT, ITEM, INVEN
		, BUBBLE, UI, UI2, BUTTON, END };
}

namespace WEAPON
{
	enum ID { BIGSWORD, SPEAR, BOW, END };
}

namespace DIR
{
	enum DIR { LEFT, RIGHT, UP, DOWN, END };
}

namespace POTAL
{
	enum ID { POTAL_A, POTAL_B, POTAL_C, END };
}

namespace EFFECT
{
	enum ID { WAVE, DASH, ROCK_EFFECT, END };
}

namespace UI
{
	enum ID { PLAYER_HPBAR, PLAYER_HP, BOSS_HPBAR, BOSS_HP, END};
}

namespace PLANT
{
	enum HEAD { HEAD_IDLE, HEAD_POTS, HEAD_JUMP, HEAD_STARTSHAKE, HEAD_CYCLESHAKE, HEAD_ENDSHAKE, HEAD_DEATH, HEAD_END };

	enum BODY { BODY_IDLE, BODY_STEM, BODY_JUMP, BODY_DEATH, BODY_END };
}

namespace PARTICLE
{
	enum EXTRA { EXTRA_WAKEUP, EXTRA_DEATH, EXTRA_END };

	enum HEAD { HEAD_IDLE, HEAD_SHOT, HEAD_END };
}

namespace NPC
{
	enum REACTION { ALERT, ANGRY, CHEAP, DOUBT, EXPENSIVE, THINK, TOO_CHEAP, TOO_EXPENSIVE, TRANSITION, END };
}